sudo: required
language: node_js
node_js:
  - '9'
services:
  - docker
branches:
  only:
    - master
    - develop
    - "/^v\\d+\\.\\d+\\.\\d+(-\\w+)?$/"
stages:
  - lint
  - test
  - deploy
jobs:
  include:
    - stage: lint
      script:
        - set -e
        - npm link
        - npm run lint
        - npm run compile
        - set +e
    - stage: test
      script:
        - set -e
        - npm link
        - npm run test
        - set +e
      after_success:
        - set -e
        - npm run test:coverage
        - cat ./coverage/lcov.info | npx coveralls
        - set +e
    - stage: deploy
      if: tag IS present
      script:
        - set -e
        - npm link
        - npx truffle migrate --network infura_rinkeby
        - npx ghu issue -k "$GITHUB_API_TOKEN" -o pandoraboxchain -r pyrrha-webclient,pyrrha-pynode,pyrrha-boxproxy,pyrrha -t "Contracts addresses update required" -b "Pandora:$(< ./build/addresses/Pandora.json), PandoraMarket:$(< ./build/addresses/PandoraMarket.json)"
        - set +e
